name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest" # or pin to an specific version, e.g. "0.7.1"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Earthly version
        run: earthly --version
      - name: Lint
        run: earthly +lint
      - name: Test
        run: earthly +test
      - name: Build Release Binary (arm64 for comma device)
        run: earthly --push +build-release
      - uses: actions/upload-artifact@v3
        with:
          name: mapd
          path: build/mapd
